# Script kiểm tra HAProxy — nếu HAProxy chết thì nhường VIP cho BACKUP
vrrp_script chk_haproxy {
    script "/etc/keepalived/check_haproxy.sh"
    interval 2        # Kiểm tra mỗi 2 giây
    weight -20        # Nếu script fail → trừ 20 điểm priority → BACKUP thắng
    fall 2            # Fail 2 lần liên tiếp mới tính là DOWN
    rise 2            # Pass 2 lần liên tiếp mới tính là UP
}

vrrp_instance VI_1 {

    state MASTER              # Trạng thái: MASTER
    interface enp0s8          # Card mạng dùng để gán IP ảo (kiểm tra bằng: ip a)

    virtual_router_id 51      # ID nhóm — 2 VM phải giống nhau

    priority 101              # Độ ưu tiên MASTER (cao hơn BACKUP)
    advert_int 1              # Gửi heartbeat mỗi 1 giây

    authentication {
        auth_type PASS
        auth_pass 1234        # Mật khẩu — 2 VM phải giống nhau
    }

    virtual_ipaddress {
        192.168.56.100        # VIP — client truy cập IP này
    }

    track_script {
        chk_haproxy           # Theo dõi HAProxy, nếu chết → nhường VIP
    }
}
