vrrp_instance VI_1 {        

    state MASTER              # Trạng thái: MASTER 

    interface enp0s8          # Card mạng dùng để gán IP ảo 

    virtual_router_id 51      # ID nhóm 

    priority 101              # Độ ưu tiên 
    # BACKUP dùng 100 (thấp hơn)

    advert_int 1              # Thời gian gửi tín hiệu kiểm tra (1 giây)

    authentication {
        auth_type PASS        # Kiểu xác thực đơn giản
        auth_pass 1234        # Mật khẩu (2 máy phải giống nhau)
    }

    virtual_ipaddress {
        192.168.56.100        # VIP (IP ảo) → client sẽ truy cập IP này
    }
}
