# Proxy Headers + No-Cache
# (include boi nginx.conf → location /)

# Gui thong tin that cua client cho backend
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

# Tat cache trinh duyet de thay load balancing khi F5
add_header Cache-Control "no-cache, no-store, must-revalidate";
add_header Pragma "no-cache";
add_header Expires 0;

# Cấu hình Timeout (Để kích hoạt cơ chế né server bận)
proxy_read_timeout 10s; # Nếu server không phản hồi trong số giây quy định, coi như lỗi
proxy_connect_timeout 5s;
proxy_next_upstream error timeout http_500 http_503 http_504; # Các lỗi sẽ khiến Nginx nhảy sang server tiếp theo





















