# Proxy Headers + No-Cache
# (include boi nginx.conf → location /)

# Gui thong tin that cua client cho backend
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

# Tat cache trinh duyet de thay load balancing khi F5
add_header Cache-Control "no-cache, no-store, must-revalidate";
add_header Pragma "no-cache";
add_header Expires 0;
