# Rate Limiting - Chong DDoS
# (include boi nginx.conf → http block)

# Gioi han moi IP chi duoc gui 10 request/giay
# Zone "one": dung 10MB RAM de luu trang thai cac IP
limit_req_zone $binary_remote_addr zone=one:10m rate=10r/s;
